### ISSUE TITLE
Uncaught TypeError: Cannot read property 'observeSelections' of undefined

### ISSUE THREAD

**Issue by gusbemacbe** [electriccode/atom-name-that-color#1]
I wasn't stopped receiving the notification of this same issue overtime I open each file. 

1. ...
2. ...

**Atom**: 1.15.0-beta1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-name-that-color](https://github.com/electriccode/atom-name-that-color) package 0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'observeSelections' of undefined

```
At /Users/gusbemacbe/.atom/packages/atom-name-that-color/lib/name-that-color.js:20

TypeError: Cannot read property 'observeSelections' of undefined
    at /packages/atom-name-that-color/lib/name-that-color.js:20:13
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:581:16)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
  2x -2:41.9.0 core:save (input.hidden-input)
     -2:23.4.0 core:backspace (input.hidden-input)
  3x -2:22.8.0 core:save (input.hidden-input)
     -1:33.5.0 core:backspace (input.hidden-input)
     -1:33 core:save (input.hidden-input)
     -1:31 editor:newline (input.hidden-input)
     -1:27.3.0 autocomplete-plus:confirm (input.hidden-input)
     -1:27.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:19.7.0 core:save (input.hidden-input)
     -1:13.9.0 editor:toggle-soft-wrap (input.hidden-input)
  3x -0:48.5.0 core:backspace (input.hidden-input)
     -0:41.6.0 core:save (input.hidden-input)
     -0:16.8.0 core:move-up (input.hidden-input)
     -0:16.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:16.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:14.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angular2-snippets 0.3.0 
ascii-unicode-escape 0.2.2 
atom-beautify 0.29.17 
atom-bootstrap4 1.4.0 
atom-clock 0.1.3 
atom-live-server 1.2.5 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-name-that-color 0.1.3 
atom-python-run 0.7.3 
autocomplete-java 1.2.5 
color-picker 2.2.5 
css-declaration-sorter 0.4.0 
data-atom 0.24.1 
dracula-theme 2.0.0 
dracula-ui 0.4.1 
drop-base64-encoding 0.2.0 
file-icons 2.0.15 
format-sql 0.3.0 
gcc-make-run 0.2.9 
hyperclick 0.0.40 
language-arduino 0.4.2 
language-latex 1.0.0 
language-oracle 1.6.2 
language-pfm 0.82.0 
language-pgsql 0.2.3 
language-sql-mysql 0.3.1 
language-tex 0.4.0 
latex 0.42.3 
latex-autocomplete 1.0.0 
latex-completions 0.3.2 
latex-friend 0.0.11 
latex-plus 0.9.1 
latexer 0.3.0 
latextools 0.8.5 
linter 1.11.21 
linter-chktex 1.3.0 
linter-javac 1.9.4 
linter-sass-lint 1.7.4 
markdown-preview-plus 2.4.1 
markdown-themeable-pdf 1.2.0 
material 2.2.0 
open-recent 5.0.0 
pdf-view 0.54.0 
php-cs-fixer 4.1.0 
php-server 0.7.0 
pigments 0.39.0 
preview-inline 1.4.5 
px-to-em 2.6.3 
recent-projects 0.13.1 
script 3.14.1 
sort-attributes 0.2.4 
sort-lines 0.14.0 
tag 0.4.0 
titanium-alloy 0.13.8 
uppercatom-letter 0.1.0 
```

**Comment by electriccode** [comment]
You're running Beta version of Atom which is experimental and can cause any plugin to break. However, this bug should get fixed along with version 0.2.0 so please update to the latest version, restart Atom and close this issue if it gets fixed.

**Comment by electriccode** [comment]
Closing this. Please reopen if required.

**Comment by gusbemacbe** [comment]
Sorry, @electriccode, for my absence, because I was busy with my college. I tested it and it worked, no errors. Thank you!
