### ISSUE TITLE
Uncaught TypeError: editor.observeSelections is not a function

### ISSUE THREAD

**Issue by plroger** [electriccode/atom-name-that-color#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-name-that-color](https://github.com/electriccode/atom-name-that-color) package 0.1.3

### Stack Trace

Uncaught TypeError: editor.observeSelections is not a function

```
At C:\Users\plrog\.atom\packages\atom-name-that-color\lib\name-that-color.js:20

TypeError: editor.observeSelections is not a function
    at /packages/atom-name-that-color/lib/name-that-color.js:20:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
  3x -8:38.1.0 core:backspace (input.hidden-input)
  2x -8:01.7.0 core:delete (input.hidden-input)
  2x -2:31.2.0 name-that-color:name-selection (span.syntax--constant.syntax--numeric.syntax--color.syntax--hex-value.syntax--scss)
     -2:15.4.0 core:delete (input.hidden-input)
     -2:05.3.0 name-that-color:name-selection (span.syntax--constant.syntax--numeric.syntax--color.syntax--hex-value.syntax--scss)
     -1:55.5.0 core:delete (input.hidden-input)
     -1:45.4.0 name-that-color:name-selection (span.syntax--constant.syntax--numeric.syntax--color.syntax--hex-value.syntax--scss)
     -1:38.3.0 core:delete (input.hidden-input)
  2x -1:35.7.0 core:undo (input.hidden-input)
     -1:29.8.0 name-that-color:name-selection (span.syntax--constant.syntax--numeric.syntax--color.syntax--hex-value.syntax--scss)
     -1:23.4.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-name-that-color 0.1.3 
```

**Comment by electriccode** [comment]
Please update your package to 0.2.0 and restart atom.
